services:
  - type: web
    name: hardwell-underwriting-automation
    env: python
    buildCommand: pip install -r requirements.txt && chmod +x start.sh
    startCommand: ./start.sh
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.19
